name: Build And Publish 
on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push -tag v1.0.0
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: 

    - name: Checkout
      uses: actions/checkout@master
    
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    
    - name: Install and Build
      run: |
        npm install
        npm run build
        mkdir site
        mv src/* site/
        mv dist/* site/

    - name: Release
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch

    # # 第二步：发布 Release
    # - name: Create Release # 创建Release，可以在仓库看到一个个版本
    #   id: create_release
    #   uses: actions/create-release@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 之前GitHub添加的Token
    #   with:
    #     tag_name: ${{ github.ref }} # (tag)标签名称
    #     release_name: Release ${{ github.ref }}
    #     draft: false # 是否是草稿
    #     prerelease: false # 是否是预发布